# Mobile Phone Plan Comparator

Welcome! In this notebook, we'll build a program to compare different mobile phone plans (prepaid and postpaid) and help you find the best value for your money.  

Think of it like comparing your SSLC mark sheet – you had subjects and marks, and you probably compared them to see which subject you scored the highest in. Here, we'll compare plans based on price, data, validity, and more.  

We'll use everything you've learned so far:  
- **Data types** (`int`, `float`, `str`, `bool`)  
- **Operations** (arithmetic, comparison, logical)  
- **Data structures** (lists, dictionaries)  
- **Control flow** (`if`, `for`, `while`)  
- **Functions** (defining, parameters, return values, and even a tiny lambda)  

No extra libraries – just pure Python. Let's dive in!

---

## Step 1: Representing a Single Plan with a Dictionary

A mobile plan has several details:  
- Name  
- Price (in rupees)  
- Data included (in GB)  
- Calls (e.g., unlimited or limited minutes)  
- Validity (in days)  
- Type (prepaid or postpaid)  

A **dictionary** is perfect for storing this kind of structured information.

In [1]:
# Example: a prepaid plan
plan = {
    'name': 'Prepaid 299',
    'price': 299,            # rupees
    'data_gb': 3,             # GB
    'calls': 'Unlimited',
    'validity_days': 28,
    'type': 'prepaid'
}

print("One plan:")
print(plan)

One plan:
{'name': 'Prepaid 299', 'price': 299, 'data_gb': 3, 'calls': 'Unlimited', 'validity_days': 28, 'type': 'prepaid'}


---

## Step 2: Storing Multiple Plans in a List

Now let's create a few different plans and store them in a list. Each plan is a dictionary. This will let us loop through them later.


In [2]:

# List of mobile plans
plans = [
    {
        'name': 'Prepaid 299',
        'price': 299,
        'data_gb': 3,
        'calls': 'Unlimited',
        'validity_days': 28,
        'type': 'prepaid'
    },
    {
        'name': 'Prepaid 599',
        'price': 599,
        'data_gb': 6,
        'calls': 'Unlimited',
        'validity_days': 56,      # 56 days validity
        'type': 'prepaid'
    },
    {
        'name': 'Postpaid 699',
        'price': 699,
        'data_gb': 20,
        'calls': 'Unlimited',
        'validity_days': 30,      # monthly plan
        'type': 'postpaid'
    },
    {
        'name': 'Postpaid 999',
        'price': 999,
        'data_gb': 40,
        'calls': 'Unlimited',
        'validity_days': 30,
        'type': 'postpaid'
    }
]

In [3]:
print("We have", len(plans), "plans in our list.")
for p in plans:
    print(" -", p['name'])

We have 4 plans in our list.
 - Prepaid 299
 - Prepaid 599
 - Postpaid 699
 - Postpaid 999



---

## Step 3: Writing Helper Functions to Calculate Important Metrics

To compare plans fairly, we need to normalise them to a common time period.  
- **Monthly cost**: How much you pay per 30 days.  
- **Monthly data**: How much data you get per 30 days.  
- **Cost per GB**: Monthly cost divided by monthly data.  

We'll write small functions to compute these.

In [4]:
def monthly_cost(plan):
    """Calculate cost for 30 days based on plan's validity and price."""
    # price is for 'validity_days', so cost per day = price / validity_days
    cost_per_day = plan['price'] / plan['validity_days']
    return cost_per_day * 30

def monthly_data(plan):
    """Calculate data provided in 30 days."""
    data_per_day = plan['data_gb'] / plan['validity_days']
    return data_per_day * 30

def cost_per_gb(plan):
    """Cost per GB based on monthly cost and monthly data."""
    m_cost = monthly_cost(plan)
    m_data = monthly_data(plan)
    if m_data == 0:   # just in case a plan has 0 data (not here)
        return float('inf')
    return m_cost / m_data

Let's test these functions on one plan.

In [5]:
# Test on the first prepaid plan
p = plans[0]
print(f"Plan: {p['name']}")
print(f"Monthly cost: ₹{monthly_cost(p):.2f}")
print(f"Monthly data: {monthly_data(p):.2f} GB")
print(f"Cost per GB: ₹{cost_per_gb(p):.2f}")


Plan: Prepaid 299
Monthly cost: ₹320.36
Monthly data: 3.21 GB
Cost per GB: ₹99.67


---
## Step 4: Display Metrics for All Plans

Now we'll loop through our list and print a nice summary table.


In [6]:

print("Plan Name            | Monthly Cost | Monthly Data | Cost/GB  | Type")
print("-" * 70)

for p in plans:
    name = p['name']
    mon_cost = monthly_cost(p)
    mon_data = monthly_data(p)
    cpg = cost_per_gb(p)
    ptype = p['type']
    
    # f-string formatting to align columns
    print(f"{name:20} | ₹{mon_cost:10.2f} | {mon_data:9.2f} GB | ₹{cpg:7.2f} | {ptype}")


Plan Name            | Monthly Cost | Monthly Data | Cost/GB  | Type
----------------------------------------------------------------------
Prepaid 299          | ₹    320.36 |      3.21 GB | ₹  99.67 | prepaid
Prepaid 599          | ₹    320.89 |      3.21 GB | ₹  99.83 | prepaid
Postpaid 699         | ₹    699.00 |     20.00 GB | ₹  34.95 | postpaid
Postpaid 999         | ₹    999.00 |     40.00 GB | ₹  24.97 | postpaid




Notice the **Prepaid 599** has 56 days validity – its monthly cost and data are almost the same as the 299 plan because it's essentially two months' worth bundled. The cost per GB is very close.

---

## Step 5: Getting User Input for Personal Usage

Now let's ask the user about their needs. We'll keep it simple: ask for the approximate data they need per month.


In [7]:
# Get user input
user_data_needed = float(input("How many GB of data do you need per month? "))
print(f"You need {user_data_needed} GB per month.\n")

How many GB of data do you need per month?  20


You need 20.0 GB per month.



*(When you run this cell, Jupyter will prompt you to enter a value. Type a number like 20 and press Enter.)*

---

## Step 6: Comparing Plans Based on User's Data Need

We'll add a column that shows whether each plan provides enough data per month (by itself) to meet the user's requirement. We'll also highlight the best value plan (lowest cost per GB) later.


In [8]:
print("Plan Name            | Monthly Cost | Monthly Data | Meets Need? | Cost/GB")
print("-" * 80)

for p in plans:
    name = p['name']
    mon_cost = monthly_cost(p)
    mon_data = monthly_data(p)
    meets = mon_data >= user_data_needed
    cpg = cost_per_gb(p)
    
    meets_str = "Yes" if meets else "No"
    print(f"{name:20} | ₹{mon_cost:10.2f} | {mon_data:9.2f} GB | {meets_str:11} | ₹{cpg:7.2f}")


Plan Name            | Monthly Cost | Monthly Data | Meets Need? | Cost/GB
--------------------------------------------------------------------------------
Prepaid 299          | ₹    320.36 |      3.21 GB | No          | ₹  99.67
Prepaid 599          | ₹    320.89 |      3.21 GB | No          | ₹  99.83
Postpaid 699         | ₹    699.00 |     20.00 GB | Yes         | ₹  34.95
Postpaid 999         | ₹    999.00 |     40.00 GB | Yes         | ₹  24.97



From this table, you can see which plans give you enough data and what they cost.

---

## Step 7: Ranking Plans by Best Value (Cost per GB)

We can sort the plans by cost per GB (lowest first) to see the best value. Python's `sorted()` function with a **lambda** is perfect for this.


In [9]:
# Sort plans by cost per GB
sorted_plans = sorted(plans, key=lambda p: cost_per_gb(p))

print("Rank | Plan Name            | Cost/GB  | Monthly Cost | Monthly Data")
print("-" * 70)

for rank, p in enumerate(sorted_plans, start=1):
    name = p['name']
    cpg = cost_per_gb(p)
    mon_cost = monthly_cost(p)
    mon_data = monthly_data(p)
    print(f"{rank:4} | {name:20} | ₹{cpg:7.2f} | ₹{mon_cost:10.2f} | {mon_data:9.2f} GB")


Rank | Plan Name            | Cost/GB  | Monthly Cost | Monthly Data
----------------------------------------------------------------------
   1 | Postpaid 999         | ₹  24.97 | ₹    999.00 |     40.00 GB
   2 | Postpaid 699         | ₹  34.95 | ₹    699.00 |     20.00 GB
   3 | Prepaid 299          | ₹  99.67 | ₹    320.36 |      3.21 GB
   4 | Prepaid 599          | ₹  99.83 | ₹    320.89 |      3.21 GB



The postpaid plans are clearly cheaper per GB, but they have higher monthly costs. The prepaid plans are expensive per GB but have lower upfront cost. Depending on your usage and budget, you can choose.

---

## Step 8: Adding a Twist – Considering Both Prepaid and Postpaid

We already have both types. But let's add a **filter** so the user can choose to see only prepaid or only postpaid plans. This demonstrates conditional logic and reusing our functions.



In [10]:

plan_type = "prepaid"

filtered_plans = []
for p in plans:
    if plan_type == 'all' or p['type'] == plan_type:
        filtered_plans.append(p)

if not filtered_plans:
    print("No plans of that type found.")
else:
    print(f"\n{plan_type.title()} plans:")
    print("Plan Name            | Monthly Cost | Monthly Data | Cost/GB")
    print("-" * 60)
    for p in filtered_plans:
        name = p['name']
        mon_cost = monthly_cost(p)
        mon_data = monthly_data(p)
        cpg = cost_per_gb(p)
        print(f"{name:20} | ₹{mon_cost:10.2f} | {mon_data:9.2f} GB | ₹{cpg:7.2f}")



Prepaid plans:
Plan Name            | Monthly Cost | Monthly Data | Cost/GB
------------------------------------------------------------
Prepaid 299          | ₹    320.36 |      3.21 GB | ₹  99.67
Prepaid 599          | ₹    320.89 |      3.21 GB | ₹  99.83




---

## Summary and Possible Extensions

🎉 **What you've learned and practiced:**  
- Using **dictionaries** to represent real-world objects (mobile plans).  
- Storing multiple records in a **list** and iterating with `for`.  
- Writing **functions** to calculate derived values (monthly cost, cost per GB).  
- Getting **user input** with `input()`.  
- Using **conditional statements** to filter data.  
- Sorting with `sorted()` and a **lambda** function.  
- Formatting output neatly with f-strings.  

🚀 **Possible extensions you could try on your own:**  
- Include **calls and SMS** – ask user for minutes/texts needed and check if plan meets them.  
- Compute **annual cost** and sort by it.  
- Handle **multiple purchases** – e.g., if a plan doesn't give enough data, how many packs would you need to buy and what would be the total cost? (Hint: use `math.ceil` after importing `math`).  
- Let the user enter their **current plan** and compare it with others.  
- Add more plans from real providers in Kerala (Jio, Airtel, BSNL, etc.).  

Remember, programming is about breaking problems into small pieces. You've just built a useful tool step by step. Keep experimenting!  

**Happy coding!**